# Generated by Django 5.0.2 on 2024-03-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_follow_id_alter_likes_id_alter_stream_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='noteDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FileField(upload_to='notes/')),
                ('title', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('field', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('exp_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
