# Generated by Django 3.1 on 2024-03-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20240315_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='notedetails',
            name='preview_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
