# Generated by Django 3.1 on 2024-03-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0007_alter_profile_id_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preview_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
