# Generated by Django 3.1 on 2024-03-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0009_remove_profile_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preview_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
