# Generated by Django 3.1 on 2024-03-15 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0010_profile_preview_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='preview_image',
        ),
    ]
