# Generated by Django 3.1 on 2024-03-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0011_remove_profile_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_no',
            field=models.IntegerField(null=True),
        ),
    ]
